apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: notification-service
          envFrom:
            - configMapRef:
                name: notification-service-config
          ports:
            - name: http
              containerPort: 4000
          # Liveness probe - checks if container is alive
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Readiness probe - checks if service is ready (DB connected)
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          # Startup probe - gives more time for initial startup
          startupProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: ClusterIP
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: notification
