export const SUCCESS_MESSAGES = {
    NOTIFICATION_COMPLETED: 'Notification process completed',
    SEND_NOTIFICATION: '/send Notification',
    NOTIFICATION_QUEUE_SAVE_SUCCESSFULLY: 'Notification saved in queue successfully',
    NOTIFICATION_SENT_SUCCESSFULLY: 'Notification sent successfully',
    PUSH_NOTIFICATION_SEND_SUCCESSFULLY: 'Push notification sent successfully',
    TEMPLATE_CREATE: 'Template created successfully',
    TEMPLATE_UPDATE: 'Template updated successfully',
    TEMPLATE_DELETE: 'Template delete successfully',
    TEMPLATE_GET: 'Template get successfully',
    CREATE_TEMPLATE_API: '/create Template for Notification',
    UPDATE_TEMPLATE_API: '/Update Template for Notification',
    TEMPLATE_DELETE_ID: (actionId) => `Template id: ${actionId} deleted successfully.`,
    TEMPLATE_LIST: 'Get template list',
    CREATED: 'Created'
};
export const ERROR_MESSAGES = {
    INVALID_REQUEST: "Invalid request",
    NOT_FOUND: "Not found",
    UNAUTHORIZED: "Unauthorized",
    FORBIDDEN: "Forbidden",
    BAD_REQUEST: "Bad request",
    INVALID_REQUEST_BODY: "Invalid request body",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    TEMPLATE_NOTFOUND: 'Template not found',
    NOTIFICATION_FAILED: `Failed to Send Notification`,
    TEMPLATE_CONFIG_NOTFOUND: 'Template Config not found for this context: ',
    NOTIFICATION_QUEUE_SAVE_FAILED: 'Failed to save notifications in queue',
    NOTIFICATION_LOG_SAVE_FAILED: 'Failed to save Log of notification',
    TOPIC_NOTIFICATION_FAILED: 'Failed to send topic notification',
    PUSH_NOTIFICATION_FAILED: 'Failed to send push notification',
    TEMPLATE_ALREADY_EXIST: 'Template already exist',
    TEMPLATE_NOT_EXIST: 'Template not exist',
    TEMPLATE_NOT_DELETED: 'Template not deleted',
    TEMPLATE_ID_NOTFOUND: (template_id) => `No template id found: ${template_id}`,
    QUEUE_NOTFOUND: 'No data found in queue',
    QUEUE_UPDATE: (id) => `No notification queue found for:${id}`,
    EVENT_UPDATE_FAILED: 'Event update failed'
}